# Generated by Django 2.2 on 2019-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
