# Generated by Django 2.2 on 2019-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0002_topic_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
