# Generated by Django 2.2 on 2019-05-26 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_auto_20190525_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_updated',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='views_count',
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
