# Generated by Django 2.2 on 2019-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0004_auto_20190526_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
